[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[profile.via_ir]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
via_ir = true
evm_version = "paris"

[profile.networks.mainnet]
url = "${ETH_RPC_URL}"
accounts = ["${PRIVATE_KEY}"]

[profile.networks.buildbear]
url = "https://rpc.buildbear.io/foolish-darkphoenix-2fe074ec"
accounts = ["${PRIVATE_KEY}"]
chainId = 25875
