[profile.default]
src = "src"
out = "out"
libs = ["lib"]
# Mainnet-compatible settings
evm_version = "shanghai"  # Latest EVM version for mainnet
optimizer = true
optimizer_runs = 200
# BuildBear specific settings
etherscan_api_key = "${ETHERSCAN_API_KEY}"
# Gas settings for mainnet
gas_reports = ["*"]
gas_reports_ignore = ["Mock", "Test"]
# Verbosity for better debugging
verbosity = 4

[profile.via_ir]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
via_ir = true
evm_version = "shanghai"  # Latest EVM version for mainnet
# BuildBear specific settings
etherscan_api_key = "${ETHERSCAN_API_KEY}"
# Gas settings
gas_reports = ["*"]
gas_reports_ignore = ["Mock", "Test"]
# Verbosity for better debugging
verbosity = 4