[profile.default]
src = "src"
out = "out"
libs = ["lib", "node_modules"]
optimizer = true
optimizer_runs = 1000
solc = "0.8.30"
via_ir = true
fs_permissions = [{ access = "read", path = "./config/" }]


[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

[profile.via_ir]
src = "src"
out = "out"
libs = ["lib", "node_modules"]
optimizer = true
optimizer_runs = 200
via_ir = true
evm_version = "paris"

[profile.networks.buildbear]
url = "https://rpc.buildbear.io/foolish-darkphoenix-2fe074ec"
accounts = ["${PRIVATE_KEY}"]
chainId = 25875

[etherscan]
mainnet = { key = "${API_KEY_ETHERSCAN}" }
polygon = { key = "${API_KEY_POLYGONSCAN}" }
base = { key = "${API_KEY_BASESCAN}" }

[rpc_endpoints]
mainnet = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"
polygon = "https://polygon-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"
base = "https://base-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"
