# Core.sol contract

**Running Notes**

**State Variables**

**Functions**

- `executeTrades()`
A functionality whose purpose is the settling of queued orders through in-contract identified DEX routes. This is the endpoint for a bot. 

**MUST** 

- cache the latest `gasPrice()` on each call

**Events**

**Errors**

**Interfaces**

**Requirements**

