# .github/workflows/settlement-bot.yml
name: Settlement Bot (cron)

on:
  schedule:
    - cron: "*/1 * * * *" # run every 5 minutes
  workflow_dispatch:
    inputs:
      mode:
        description: "Run mode (only 'once' supported in CI)"
        required: true
        default: "once"
        type: choice
        options: ["once"]

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    defaults:
      run:
        working-directory: bot # 👈 run commands inside your /bot dir
    env:
      # secrets — set these in GitHub → Settings → Secrets → Actions
      RPC_HTTP_URL: ${{ secrets.RPC_HTTP_URL }}
      CONTRACT_ADDRESS: "0x3875b8b82e58733c1667224eb8bf5f449d7dbb74"
      DEPLOYMENT_BLOCK: "23291452"
      PRIVATE_KEY: ${{ secrets.DFGSDFGTEH_PRIVATE_KEY }}
      CHAIN_ID: "1"

      # optional non-secret config (can also be repo variables)
      # LOG_CHUNK: ${{ vars.LOG_CHUNK || '2000' }}
      STATE_FILE: ${{ vars.STATE_FILE || './state.json' }}
      # MAX_PARALLEL_TX: ${{ vars.MAX_PARALLEL_TX || '3' }}
      # GAS_MULTIPLIER: ${{ vars.GAS_MULTIPLIER || '1.1' }}
      # CONFIRMATIONS: ${{ vars.CONFIRMATIONS || '2' }}
      WS_URL: ${{ secrets.WS_URL }} # not needed in cron mode
    steps:
      - uses: actions/checkout@v4

      - name: Verify bot directory exists
        run: |
          echo "Current directory: $(pwd)"
          echo "Contents of current directory:"
          ls -la
          echo "Looking for bot directory:"
          find . -name "bot" -type d 2>/dev/null || echo "No bot directory found"
          echo "Looking for bot files:"
          find . -name "package.json" -path "*/bot/*" 2>/dev/null || echo "No bot package.json found"

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: bot/package.json

      - name: Install dependencies
        run: |
          if [ -d "bot" ]; then
            cd bot
            npm ci
          else
            echo "Bot directory not found, checking if we need to create it"
            find . -name "package.json" -path "*/bot/*" -exec dirname {} \;
          fi

      - name: Build bot
        run: |
          if [ -d "bot" ]; then
            cd bot
            npm run build
          else
            echo "Cannot build - bot directory not found"
            exit 1
          fi

      - name: Run bot
        run: |
          if [ -d "bot" ]; then
            cd bot
            node dist/index.js --mode ${{ github.event.inputs.mode || 'once' }}
          else
            echo "Cannot run - bot directory not found"
            exit 1
          fi

      - name: Upload state.json
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: state-${{ github.run_id }}
          path: bot/state.json
          if-no-files-found: warn
